receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  


processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  # Remove resource processor to avoid label duplication
  # Labels are now set directly by the application

exporters:
  # Prometheus exporter
  prometheus:
    endpoint: "0.0.0.0:8889"
    # Remove const_labels to avoid duplication
  
  # OTLP exporter for Jaeger (using internal Docker network)
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  
  # Debug exporter for debugging (replaces deprecated logging exporter)
  debug:
    verbosity: normal

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]

  extensions: []
