receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  prometheus:
    config:
      scrape_configs:
        - job_name: 'redis-test-app'
          static_configs:
            - targets: ['redis-test-app:8000']
          scrape_interval: ${PROMETHEUS_SCRAPE_INTERVAL:-5s}
          metrics_path: /metrics

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  resource:
    attributes:
      - key: service.name
        value: redis-py-test-app
        action: upsert
      - key: deployment.environment
        value: docker
        action: upsert

exporters:
  # Prometheus exporter
  prometheus:
    endpoint: "0.0.0.0:8888"
    namespace: redis_test
    const_labels:
      environment: docker
  
  # Jaeger exporter
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  
  # Logging exporter for debugging
  logging:
    loglevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [jaeger, logging]
    
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch, resource]
      exporters: [prometheus, logging]

  extensions: []
